import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Subscription</Link>
        </li>
        <li>
          <Link to="/pendants">Pendants</Link>
        </li>
        <li>
          <Link to="/bracelets">Bracelets</Link>
        </li>
        <li>
          <Link to="/necklaces">Necklaces</Link>
        </li>
        <li>
          <Link to="/gifting">Gifting</Link>
        </li>
        <li>
          <Link to="/home1">HOME1</Link>
        </li>
        <li>
          <Link to="/thehazeexperience">TheHazeExperience</Link>
        </li>
        <li>
          <Link to="/wishlist">Wishlist</Link>
        </li>
        <li>
          <Link to="/accountdetails">Accountdetails</Link>
        </li>
        <li>
          <Link to="/orderdetails">OrderDetails</Link>
        </li>
        <li>
          <Link to="/help">Help</Link>
        </li>
        <li>
          <Link to="/cart">Cart</Link>
        </li>
        <li>
          <Link to="/earrings">Earrings</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/forgotpassword">Forgotpassword</Link>
        </li>
        <li>
          <Link to="/signup">Signup</Link>
        </li>
        <li>
          <Link to="/signupnext">Signupnext</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
